### ISSUE TITLE
Getting started documentation, separate READMEs

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#10]
### Description

If the README in the main project were smaller, I think it'd be a bit easier to follow.

For example, the main repo should only a brief description 3 main parts, the skeleton and the 2 bundles, and links.

The skeleton could be run out of the box with a few small changes:

* change the .env file to use a SQLITE database for the default DATABASE_URL
* add bin/console create:admin_user to the instructions
* Either add a username to the admin_user, or change the login page to say email/username.  

Then a link to how to create an entity or table or some of the cool features umbrella has.

**Comment by acantepie** [comment]
I have updated the doc and depreciate the usage of skeleton to clarify install process.
In replacment of skeleton, i have created (bin/console make:admin:home) / updated maker.
