### ISSUE TITLE
Clarify license for Hyper Admin Theme

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#11]
### Description

I really like this bundle and would like to use it with some of my projects.  

I'm concerned about the license, though, as it's based on this theme:

https://themes.getbootstrap.com/product/hyper-responsive-admin-dashboard-template/

But it appears that the license doesn't cover embedding the theme in a framework:

https://themes.getbootstrap.com/licenses/

Can you please clarify?

**Comment by tacman** [comment]
What do you think about replacing hyper-theme with tabler (https://tabler.io/)?  It's MIT licensed.

**Comment by acantepie** [comment]
Hello,
I have asked question to their support.

I will look at an other bootsrap5 template (tabler ?) if i have to remove theme.

**Comment by tacman** [comment]
@kevinpapst has a rudimentary bundle based on this theme:

https://github.com/kevinpapst/TablerBundle

Gut feeling is that you should switch to tabler, since it's Open Source any changes that are related to the front end can be made there, and you can focus on the integration.

Thanks.

**Comment by tacman** [comment]
I'll move this to a new thread, since it's a major change.

**Comment by tacman** [comment]
Did you hear back from them?  What are your thoughts on moving to Tabler, or some other MIT-licensed Bootstrap 5 theme?

**Comment by acantepie** [comment]
Hi,

Yeah, they answer me. Hyper licence doesn't allow bundling their theme into an open-source project.
I have tried Tabler.io but i have finally chosen [AdminKit](https://github.com/adminkit/adminkit) (Mit license for limited version).
I am working on a new version.

Branch : [4.x](https://github.com/acantepie/umbrella/tree/4.x). 
Demo : https://release.umbrella-corp.dev/

I will publish this version soon.

**Comment by tacman** [comment]
Terrific!

I like AdminKit, I even bought a license for the pro version.  But then
they gutted some features (like nested sidebar menus) that were in the free
version one day then suddenly they were gone.  This disrupted all the
projects that used them.

Since it's MIT-licensed, though, you can augment your bundle to support
nested and collapsible sidebar menus, yes?  For an admin theme, the sidebar
menu seems to be of paramount importance.

I also like the right-panel settings menu and the mega-menu that are common
in admin themes, but aren't directly supported by AdminKit.

Anyway, awesome work!  Thanks.

**Comment by tacman** [comment]
> I will publish this version soon.

When I install version 4 (composer require umbrella2/adminbundle:^4) I get an error from core about hasLink not being a method.  I imagine this will be fixed when you publish v4.

**Comment by acantepie** [comment]
> Terrific!
> 
> I like AdminKit, I even bought a license for the pro version.  But then
> they gutted some features (like nested sidebar menus) that were in the free
> version one day then suddenly they were gone.  This disrupted all the
> projects that used them.
> 
> Since it's MIT-licensed, though, you can augment your bundle to support
> nested and collapsible sidebar menus, yes?  For an admin theme, the sidebar
> menu seems to be of paramount importance.
> 
> I also like the right-panel settings menu and the mega-menu that are common
> in admin themes, but aren't directly supported by AdminKit.
> 
> Anyway, awesome work!  Thanks.

I have developed some features missing on free version like nest items on sidebar (quite easy because nest items are bs5 collapse).
Purchase a pro license doesn't allow me to redistribute theme under less restrictive license, so i won't upgrade.

> When I install version 4 (composer require umbrella2/adminbundle:^4) I get an error from core about hasLink not being a method. I imagine this will be fixed when you publish v4.

I check

**Comment by acantepie** [comment]
> When I install version 4 (composer require umbrella2/adminbundle:^4) I get an error from core about hasLink not being a method. I imagine this will be fixed when you publish v4.

To test vendor from an untagged branch, you shave to specify all vendors version :
```
composer require umbrella2/corebundle:dev-master
composer require umbrella2/adminbundle:dev-master
```
