### ISSUE TITLE
Split doesn't work for forks

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#12]
### Description

I've made some changes that I'd like to contribute to the project, but I'm not sure how to test on my repo before submitting a PR.

The split command is failing.

https://github.com/tacman/umbrella/actions/runs/1487123302

What I'd like to do, obviously, is run the github actions against my fork (and branch) first, then submit the PR.  Alas, I'm new to github actions, and am not sure how to inject the github user instead of the harcoded acantepie in the split action.

### Example

```
if [[ -n "${INPUT_GITHUB_TOKEN}" ]]
then
  BASE_REMOTE_URL="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/acantepie"
else
  BASE_REMOTE_URL="git@github.com:acantepie"
fi
```

Without hardcoding 'tacman', is there a way I can have this run against my fork?

**Comment by acantepie** [comment]
https://github.com/acantepie/umbrella/commit/a404f3c922ab1f3e01072b59c46a54cbc5ea5b5e

I have updated split job (split copy code from acantepie/umbrella on mirror repo). This job will run only for this repository.
