### ISSUE TITLE
docker installation for demo fails on nginx

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#18]
### Umbrella version affected

admin demo

### Description

Run the demo from docker.

### How to reproduce

# Clone repository
git clone git@github.com:acantepie/umbrella-admin-demo.git umbrella_demo
cd umbrella-demo

# Build / Up Docker
docker-compose up -d

Logs show:

nginx      | 2021/11/28 13:22:14 [emerg] 1#1: host not found in upstream "symfony" in /etc/nginx/conf.d/default.conf:11
nginx      | nginx: [emerg] host not found in upstream "symfony" in /etc/nginx/conf.d/default.conf:11

**Comment by acantepie** [comment]
Fix : https://github.com/acantepie/umbrella-admin-demo/commit/f39b8761ec66e7d31eaa0025b04a25c4e9d69cab

I think, the problem is service nginx started before service symfony. 

To test my fix :
```bash
# On demo project directory
git pull
docker-compose down
docker-compose up -d

# Check all services are running
docker-compose ps
```

Does-it solve your problem ?

**Comment by tacman** [comment]
Yep, thanks for fixing this!

There's a warning that installing 'intl' would improve performance, not sure how to do that, it'd be nice only because it's the only warning that's showing up right now, so it'd be nice to not see that.
