### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by filipealonso** [acantepie/umbrella#2]
Symfony operations: 2 recipes (f98f61df183401c3baddd25ca86d7b00)
  - Configuring umbrella2/corebundle (>=v2.8): From auto-generated recipe
  - Configuring umbrella2/adminbundle (>=v2.8): From auto-generated recipe

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1

> !!
> !!  In ArrayNode.php line 218:
> !!  
> !!    **The child config "home_route" under "umbrella_admin" must be configured: Route of admin home**  
> !!  
> !!
> !!

Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by filipealonso** [comment]
I assume your skeleton is required for initial setup but you should separate it from the required configuration layer in case someone wants to install it on an existing project. The skeleton would replace things like pre-existing default controller, security and routes yaml, etc... which is highly undesirable and would break everything. In my case I already have a whole project running and I just want to add the administration part, so the installation should be smooth and add the required configuration settings to the configuration files already in place.

**Comment by acantepie** [comment]
@filipealonso it was patched on release 2.9 (home_route options is not required anymore)
I will improve documentation to explain how install admin on existing project.
On src/ folder , the only mandatory class is User entity.

```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Umbrella\AdminBundle\Entity\BaseUser;
use Umbrella\CoreBundle\Search\Annotation\Searchable;

/**
 * Class User
 *
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @Searchable
 * @UniqueEntity("email")
 */
class MyAdminUser extends BaseUser
{
    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {
        return ['ROLE_ADMIN'];
    }
}
```

```
umbrella_admin:
  ...
  user:
    class: App\Entity\MyAdminUser
```

**Comment by filipealonso** [comment]
@acantepie Thank you, I appreciate it... that would make the installation process more clear.

Food for thought, and certainly is not the most common option, but what if your project uses in memory users? Will it work? Is it also mandatory to implement a custom User class? Or could you use Symfony\Component\Security\Core\User\InMemoryUser? Would it conflict or have any limitation somehow?

Cheers

**Comment by acantepie** [comment]
Hmmm, you can login with a memory user too, but on skeleton the CRUD user is "enabled" and an user entity must be defined and implement AdminUserInterface.
But i think it is possible to disable user CRUD and use admin without be authenticated (like EasyAdmin) and configure later security (and use form login view  from vendor if needed, and create an entity and use CRUD from vendor if needed).

I am looking :)

**Comment by acantepie** [comment]
@filipealonso I have updated documentation.

**Comment by filipealonso** [comment]
@acantepie awesome, thanks... will take a look and try again from scratch!
