### ISSUE TITLE
bin/console create:admin_user not visible

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#20]
### Umbrella version affected

4.x

### Description

This command isn't visible:

```
bin/console create:admin_user

[critical] Error thrown while running command "'create:admin_user'". Message: "There are no commands defined in the "create" namespace."
```

### How to reproduce

```
composer require umbrella2/adminbundle
bin/console create:admin_user
```

**Comment by acantepie** [comment]
Can you retry with last version ?

**Comment by tacman** [comment]
bin/console create:admin_user 

installs 4.2, but then 

bin/console create:admin_user

still fails.  Changing to dev-master and updating also fails.

**Comment by acantepie** [comment]
You probably forget to add config on `umbrella_admin.yaml` :

```yaml
umbrella_admin:
  user:
    class: App\Entity\AdminUser
```

I have just tested, it works as expected
```bash
composer create-project symfony/website-skeleton foo   
cd foo/
composer require umbrella2/adminbundle
php bin/console make:admin:user
php bin/console create:admin_user # No error 
```

**Comment by tacman** [comment]
Yep, you're right.

I had skipped

php bin/console make:admin:user

And the error message was that the command didn't exist.  Ideally,
that message would be that the class doesn't exist.
