### ISSUE TITLE
Make content block configurable

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#24]
### Description

I'm integrating Umbrella with a project that used Symfony's crud system to generate its templates.  The content of each page (show, edit, index, etc.) is 

```twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>{{ session }} Session</h1>
{% endblock %}
```

I've changed base.html.twig to extend from umbrella:

```twig
{% extends "@UmbrellaAdmin/layout.html.twig" %}
```

But now my page content is taking over the entire body.  Obviously, I can change my twig templates from block body to block content, but I'm hoping there's another way.

I'm wondering if using _embed_ might be the right solution.  But I can't seem to figure it out.

For now, I'm simply copying the umbrella base template into my project base template and tweaking the content block, and maybe that is in fact the right way to use umbrella.  But if there's an easy way to use umbrella with Symfony-generated crud files, it would be worth considering.

**Comment by acantepie** [comment]
Wo, why are you using Sf maker Command to generate CRUD instead of umbrella maker command ? (make:admin:table or make:admin:tree)

**Comment by tacman** [comment]
It's an older project that I'm converting to use Umbrella.

**Comment by acantepie** [comment]
I think you can just, search and replace:
```twig
{% extends "base.html.twig" %}
```
by
```twig
{% extends "@UmbrellaAdmin/layout.html.twig" %}
```

and 
```twig
{% block body %}
```
by
```twig
 {% block content %}
```
on your generated twig template.
I won't to make the name of the blocks configurable (i don't know if it's possible), your use cas is too specific (.

**Comment by tacman** [comment]
Yeah, or simply re-working your base template within an application.
