### ISSUE TITLE
Pass context/options to MenuBuilder

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#25]
### Description

I'd like to pass some context to a menu, so that I can build a menu specific to a set of page.  For example, I want to pass in an person, and based on some properties I'll generate the menu.  I'll have different menus for each part of the site.

If there's a way to configure rendering options, like classes on selected items, those could be pass in as well.  KnpMenuBundle uses this approach.

Building the menu and rendering it feel like they could be separate, though not essential.

### Example

Something like

```twig
            {% set menu = umbrella_get_menu('App\\Menu\\PersonAdminMenu', {person: person}) %}
            {{ umbrella_render_menu(menu, {currentClass: 'selected'}) }}
```

```php
namespace App\Menu;

class PersonAdminMenu extends BaseAdminMenu
{
   private Person $person;
   public function setContext(array $context) 
   { 
       $this->person = $context['person'];
   }

    public function buildMenu(MenuBuilder $builder)
    {
        $u = $builder->root();
        if ($this->person->hasBio()) {
                  $u->add('biography')
            ->route('person_bio', ['id' => $person->getId()]);
     }
```

Currently I'm passing in the related entity via the RequestStack, which feels kludgy.

**Comment by acantepie** [comment]
Hi, this is now possible on version 4.3.
I have been inspired by KnpMenuBundle for twig functions and helpers.
Take a look at [menu documentation page](https://umbrella-corp.dev/admin/menu)

Example : 
```twig
{% set menu = get_menu('App\\Menu\\PersonAdminMenu', {person: person}) %}
{{ render_menu(menu, {currentClass: 'selected'}) }}
```

**Comment by tacman** [comment]
Thanks!

As long as we're talking about menus, is there a way to render a horizontal
menu (with dropdowns?), using the same menu?

KnpMenu does that by passing in a twig template in the context.  I often
like to have a site menu in the navbar, and sometimes a page-specific menu
at the top of the page.

I know those should be relatively easy to implement, but to do it nicely
with the same look and feel is harder.  It appears that AdminKIt doesn't
have an example, but there are lots of bootstrap examples.  Now that
creating the menu is separate from rendering it, this should be doable.

**Comment by acantepie** [comment]
It's not possible to use the current menu template to render a horizontal menu because the vertical menu use collapse.
The only way i see is to create an other template for vertical variant :

```php
class AdminMenu extends BaseAdminMenu {

    public function renderMenu(Menu $menu, array $options): string
    {
        if (isset($options['layout']) && 'horizontal' === $options['layout']) {
            return $this->twig->render('menu/horizontal.html.twig', ['menu' => $menu]);
        } else {
            return parent::renderMenu($menu, $options);
        }
    }
}
```

Then
```twig
{{ render_menu(admin_menu, {'layout': 'horizontal'}) }}
```

**Comment by tacman** [comment]
But why not just allow for complete customization?

```php
class AdminMenu extends BaseAdminMenu {

    public function renderMenu(Menu $menu, array $options): string
    {
        if (isset($options['template'])) {
            return $this->twig->render($options['template'], ['menu' => $menu]);
        } else {
            return parent::renderMenu($menu, $options);
        }
    }
}
```

Which can likely be reduced further with a default template value.

**Comment by tacman** [comment]
For example, suppose I want to render a menu but want to use feather icons, or have a fancy badge.

What do you think of adding 'template' to the render options?

**Comment by acantepie** [comment]
> For example, suppose I want to render a menu but want to use feather icons, or have a fancy badge.
> 
> What do you think of adding 'template' to the render options?

Here we go https://github.com/acantepie/umbrella/commit/f7ad4d22cff2b97ae5e0935e9ba74a019d88a9f1 ^^
