### ISSUE TITLE
No config file with Symfony 6.0.1 and PHP 8.0.13

### ISSUE THREAD

**Issue by Grazulex** [acantepie/umbrella#26]
### Umbrella version affected

4.2

### Description

No config/packages/umbrella_admin.yaml file when install with :
composer require umbrella2/adminbundle
and when create manualy, nothing happend....

I have create the Admin/DefaultController.php and this route is fine.
I try to make the menu with the file : src/Menu/AdminMenu.php and with the config file but I don't find this file (config/packages/umbrella_admin.yaml).
I try to create this manualy and I put the config nut nothing happend (no menu on the screen) : 
```
umbrella_admin:
  menu: App\Menu\AdminMenu
```

### How to reproduce

composer require umbrella2/adminbundle on a clean symfony 6.0.1 installation (Debian 10 and PHP 8.0.13)

**Comment by Grazulex** [comment]
I have try to do the same with a Symfony 5.4.1 version and I have the same situation...(always on the same server with the same PHP version)

**Comment by acantepie** [comment]
Can you push your project somewhere ? i will check
