### ISSUE TITLE
[Iconscout / unicons] OTS parsing error

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#27]
### Umbrella version affected

4.x

### Description

There's something wrong with the fonts, open the console on

![image](https://user-images.githubusercontent.com/619585/148224713-0de356bc-03ab-4221-8518-5098c84d5ec4.png)

### How to reproduce

https://umbrella-corp.dev/admin/about

Open the console

**Comment by acantepie** [comment]
This issue is related to Unicons font : https://github.com/Iconscout/unicons/issues/138
