### ISSUE TITLE
How to add non-menu content in the sidebar

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#29]
### Description

Is there a way to add content below the menu?  

Adminkit has a sidebar-cta class, but I can't figure out how to insert my text there.

What I really want to do is add some options there, which will include a list of checkboxes and switches.  It will only be visible on some pages.

### Example

From layout.html.twig

```twig
   {% block body %}

            <div class="wrapper">
                {% block sidebar %}
                    {{ render_menu(admin_menu) }}

RENDER FORM HERE.
                {% endblock %}

                <div class="main">
                    {% block topbar %}      
etc..
```

**Comment by acantepie** [comment]
Hi,
You juste have to override template of vendor, check documentation here : https://symfony.com/doc/current/bundles/override.html
