### ISSUE TITLE
Opening second level menu closes parent

### ISSUE THREAD

**Issue by jeroenmimpen** [acantepie/umbrella#33]
### Umbrella version affected

6.1

### Description

When I have a sidebar-menu structure that is two levels deep, something in the javascript seems to break. When opening the second level, it actually closes the first. 

### How to reproduce

I click Catalog. It opens the sub-menu. I then click 'Zoekfilters'. And it *closes* Catalog again (it also seems to open the sub-sub-menu simultaneously).

[inklappende menu bij 2 kinderen 2022-10-10 13.21.07.webm](https://user-images.githubusercontent.com/10400659/194857346-44fe4645-18f3-4546-9cdd-68c5d3f3829d.webm)

**Comment by acantepie** [comment]
Will be fixed on next release
