### ISSUE TITLE
UmbrellaCollectionType with dropdowns hide the scrollbar

### ISSUE THREAD

**Issue by jeroenmimpen** [acantepie/umbrella#34]
### Umbrella version affected

6.1

### Description

Collection formtypes with dropdowns hide the dropdown behind other HTML elements.

### How to reproduce

I have an entity, which has one-to-many relation with another entity. This other entity is the pivot table (so actually, my original entity has a many-to-many relation) between this entity and another. This pivot table entity has an AutocompleteType to select this entity. When expanding this dropdown it opens behind other HTML elements. You need to manually scroll to be able to view its contents.

[dropdowns met dubbele scrollbar 2022-10-10 13.25.36 (1).webm](https://user-images.githubusercontent.com/10400659/194859460-64b0bead-1ab0-4f1f-8bf4-026af2d552e4.webm)

Additional example:

[ZHJvcGRvd25zIG1ldCBkdWJiZWxlIHNjcm9sbGJhciAyMDIyLTEwLTEwIDEzLjU4LjQ0LndlYm0=.webm](https://user-images.githubusercontent.com/10400659/194861884-793d4021-b766-4ac8-9ba6-c02464ca04bd.webm)

**Comment by acantepie** [comment]
Will be fixed on next release
