### ISSUE TITLE
Ordering via relation field

### ISSUE THREAD

**Issue by jeroenmimpen** [acantepie/umbrella#35]
### Umbrella version affected

6.1

### Description

Not sure if this is a bug but I cannot figure out how to get it to work. I want to sort a column that contains a many-to-one relation. The umbrella backends gives me an error.

Before:
![image](https://user-images.githubusercontent.com/10400659/195601254-8e57e4db-5464-41b6-b9cf-f0e8ee43b76f.png)

Click on the third column to sort.

After:
![image](https://user-images.githubusercontent.com/10400659/195600933-4c0b6550-99b5-4754-bf07-3bbcc192d1ea.png)

### How to reproduce

Create an entity that has a many-to-one relation with another entity (or itself, in my case).

In my case, I have a category entity, which has a many-to-one to itself, which is the 'parent-category'.

```
#[ORM\ManyToOne(targetEntity: 'App\Entity\Default\Category', inversedBy: 'categories')]
#[ORM\JoinColumn(nullable: true, name: 'parent_category_id')]
public ?Category $parent_category;
```

Adding this column to the data table builder:
```
$fieldOptions['property_path'] = 'parent_category';
$fieldOptions['order_by'] = 'parent_category.cms_label';
$builder->add('parent_category', 'Umbrella\CoreBundle\DataTable\Column\PropertyColumnType', $fieldOptions);
```

Trying to sort gives this error:
> [Semantical Error] line 0, col 72 near 'parent_category.cms_label': Error: 'parent_category' is not defined.

![image](https://user-images.githubusercontent.com/10400659/195600207-d7694abe-49d3-47b6-b1ff-286426eed1e5.png)

**Comment by acantepie** [comment]
Hi,

You have this error because the DataTable will create a doctrine query that will look like this :
`SELECT e FROM App\Foo::class e ORDER BY parent_category.cms_label ASC`

 So, you have to declare `parent_category` alias on your query : 
```php
// FooDataTableType.php

    public function buildTable(DataTableBuilder $builder, array $options)
    {
        $fieldOptions['property_path'] = 'parent_category';
        $fieldOptions['order_by'] = 'parent_category.cms_label';
        $builder->add('parent_category', 'Umbrella\CoreBundle\DataTable\Column\PropertyColumnType', $fieldOptions);

        $builder->useEntityAdapter([
            'class' => Foo::class,
            'query' => function (QueryBuilder $qb, array $formData) {
                $qb->leftJoin('e.parent_category', 'parent_category');
            }
        ]);
    }
```

**Comment by jeroenmimpen** [comment]
This works! Thanks for the example and explanation.
