### ISSUE TITLE
Use different doctrine connection for DataTableType

### ISSUE THREAD

**Issue by jeroenmimpen** [acantepie/umbrella#36]
When creating a DataTableType for an Entity for a different connection I cannot figure out how to tell this to use this connection. Currently getAdapterResult will always use the 'default' doctrine connection. 

In most other places I have access to the EntityManager (via ->em()) and I am able to pass the name. In the case of some helper functions (persistAndFlush, findOrNotFound, etc) I cannot pass the name, but I can easily overwrite these functions to make this possible.

Is there a way to accomplish this for the DataTableType classes?

**Comment by acantepie** [comment]
Hi,

I have added an option `em` for `EntityAdapterType` and `NestedEntityAdapterType` to specify the dbal connection name.
Example :

```doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                [...]
            other:
                [...]
```

```DataTableType.php

class FooTableType extends DataTableType
{
    public function buildTable(DataTableBuilder $builder, array $options)
    {
        // ...
        $builder->useEntityAdapter([
            'class' => Foo::class,
            'em' => 'other' // <-- The name of dbal connection, if not specified Adapter will use the default dbal connection
        ]);
    }
}

```

I haven't created a tag yet. To use this feature you must use `dev-master` version of Umbrella on your project : 

```composer.json
{
    "require": {
        "umbrella2/adminbundle": "dev-master",
        "umbrella2/corebundle": "dev-master"
    }
}
```

Related commit : https://github.com/acantepie/umbrella/commit/258842a62502c0c970d4155d6dcc247009eb4505

**Comment by jeroenmimpen** [comment]
Thanks! This works perfectly.
