### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by MagePsycho** [acantepie/umbrella#9]
Getting an error
>  Invalid type for path "umbrella_admin.menu". Expected "array", but got "string"

**Comment by parijke** [comment]
same

**Comment by acantepie** [comment]
Hello,
How have you installed umbrella ?
Which version of php and umbrella are you using ?

**Comment by parijke** [comment]
Followed these instructions. Tried it with php7.4 and 8.0, same error
```
composer create-project umbrella2/skeleton my_project
cd my_project/
Configure your database:

Edit the DATABASE_URL env var in the .env file to use your database credentials.
php bin/console doctrine:database:create
php bin/console doctrine:schema:create
Serve:

php -S localhost:8000 -t public/
Browse http://localhost:8000/admin and hint umbrella / umbrella to login.
```

**Comment by acantepie** [comment]
Ho, the version on composer.json was invalid.
It should work now.

**Comment by MagePsycho** [comment]
@acantepie @parijke with the mentioned change in composer.json, it worked like a charm.

**Comment by parijke** [comment]
Can confirm the install now.
